// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateSubscriptionRequest defines model for CreateSubscriptionRequest.
type CreateSubscriptionRequest struct {
	// EndDate Месяц и год в формате MM-YYYY.
	EndDate *MonthYear `json:"end_date,omitempty"`

	// Price Стоимость месячной подписки в рублях.
	Price int `json:"price"`

	// ServiceName Название сервиса, предоставляющего подписку.
	ServiceName string `json:"service_name"`

	// StartDate Месяц и год в формате MM-YYYY.
	StartDate MonthYear `json:"start_date"`

	// UserId Идентификатор пользователя.
	UserId openapi_types.UUID `json:"user_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Текст ошибки.
	Message string `json:"message"`
}

// MonthYear Месяц и год в формате MM-YYYY.
type MonthYear = string

// SubscriptionListResponse defines model for SubscriptionListResponse.
type SubscriptionListResponse struct {
	Items []SubscriptionResponse `json:"items"`

	// Limit Лимит выдачи.
	Limit int `json:"limit"`

	// Offset Смещение выдачи.
	Offset int `json:"offset"`

	// Total Общее количество записей, удовлетворяющих фильтрам.
	Total int64 `json:"total"`
}

// SubscriptionResponse defines model for SubscriptionResponse.
type SubscriptionResponse struct {
	// EndDate Месяц и год в формате MM-YYYY.
	EndDate *MonthYear `json:"end_date,omitempty"`

	// Id Идентификатор записи.
	Id openapi_types.UUID `json:"id"`

	// Price Стоимость месячной подписки в рублях.
	Price int `json:"price"`

	// ServiceName Название сервиса, предоставляющего подписку.
	ServiceName string `json:"service_name"`

	// StartDate Месяц и год в формате MM-YYYY.
	StartDate MonthYear `json:"start_date"`

	// UserId Идентификатор пользователя.
	UserId openapi_types.UUID `json:"user_id"`
}

// TotalCostResponse defines model for TotalCostResponse.
type TotalCostResponse struct {
	// Currency Валюта расчета.
	Currency string `json:"currency"`

	// EndPeriod Месяц и год в формате MM-YYYY.
	EndPeriod MonthYear `json:"end_period"`

	// StartPeriod Месяц и год в формате MM-YYYY.
	StartPeriod MonthYear `json:"start_period"`

	// TotalCost Суммарная стоимость подписок за выбранный период в рублях.
	TotalCost int `json:"total_cost"`
}

// UpdateSubscriptionRequest defines model for UpdateSubscriptionRequest.
type UpdateSubscriptionRequest struct {
	// EndDate Месяц и год в формате MM-YYYY.
	EndDate *MonthYear `json:"end_date,omitempty"`

	// Price Стоимость месячной подписки в рублях.
	Price int `json:"price"`

	// ServiceName Название сервиса, предоставляющего подписку.
	ServiceName string `json:"service_name"`

	// StartDate Месяц и год в формате MM-YYYY.
	StartDate MonthYear `json:"start_date"`

	// UserId Идентификатор пользователя.
	UserId openapi_types.UUID `json:"user_id"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// CalculateTotalCostParams defines parameters for CalculateTotalCost.
type CalculateTotalCostParams struct {
	// StartPeriod Начало периода в формате MM-YYYY.
	StartPeriod MonthYear `form:"start_period" json:"start_period"`

	// EndPeriod Конец периода в формате MM-YYYY.
	EndPeriod MonthYear `form:"end_period" json:"end_period"`

	// UserId Идентификатор пользователя в формате UUID.
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`

	// ServiceName Название сервиса подписки.
	ServiceName *string `form:"service_name,omitempty" json:"service_name,omitempty"`
}

// ListSubscriptionsParams defines parameters for ListSubscriptions.
type ListSubscriptionsParams struct {
	// UserId Идентификатор пользователя в формате UUID.
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`

	// ServiceName Название сервиса подписки.
	ServiceName *string `form:"service_name,omitempty" json:"service_name,omitempty"`

	// Limit Максимальное количество записей в ответе.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение относительно начала списка.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = CreateSubscriptionRequest

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = UpdateSubscriptionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Посчитать суммарную стоимость подписок
	// (GET /api/v1/reports/total-cost)
	CalculateTotalCost(w http.ResponseWriter, r *http.Request, params CalculateTotalCostParams)
	// Получить список подписок
	// (GET /api/v1/subscriptions)
	ListSubscriptions(w http.ResponseWriter, r *http.Request, params ListSubscriptionsParams)
	// Создать подписку
	// (POST /api/v1/subscriptions)
	CreateSubscription(w http.ResponseWriter, r *http.Request)
	// Удалить подписку
	// (DELETE /api/v1/subscriptions/{subscription_id})
	DeleteSubscription(w http.ResponseWriter, r *http.Request, subscriptionId openapi_types.UUID)
	// Получить подписку по идентификатору
	// (GET /api/v1/subscriptions/{subscription_id})
	GetSubscription(w http.ResponseWriter, r *http.Request, subscriptionId openapi_types.UUID)
	// Обновить подписку
	// (PUT /api/v1/subscriptions/{subscription_id})
	UpdateSubscription(w http.ResponseWriter, r *http.Request, subscriptionId openapi_types.UUID)
	// Проверить доступность сервиса
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Посчитать суммарную стоимость подписок
// (GET /api/v1/reports/total-cost)
func (_ Unimplemented) CalculateTotalCost(w http.ResponseWriter, r *http.Request, params CalculateTotalCostParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список подписок
// (GET /api/v1/subscriptions)
func (_ Unimplemented) ListSubscriptions(w http.ResponseWriter, r *http.Request, params ListSubscriptionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать подписку
// (POST /api/v1/subscriptions)
func (_ Unimplemented) CreateSubscription(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить подписку
// (DELETE /api/v1/subscriptions/{subscription_id})
func (_ Unimplemented) DeleteSubscription(w http.ResponseWriter, r *http.Request, subscriptionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить подписку по идентификатору
// (GET /api/v1/subscriptions/{subscription_id})
func (_ Unimplemented) GetSubscription(w http.ResponseWriter, r *http.Request, subscriptionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить подписку
// (PUT /api/v1/subscriptions/{subscription_id})
func (_ Unimplemented) UpdateSubscription(w http.ResponseWriter, r *http.Request, subscriptionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Проверить доступность сервиса
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CalculateTotalCost operation middleware
func (siw *ServerInterfaceWrapper) CalculateTotalCost(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalculateTotalCostParams

	// ------------- Required query parameter "start_period" -------------

	if paramValue := r.URL.Query().Get("start_period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start_period"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "start_period", r.URL.Query(), &params.StartPeriod, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_period", Err: err})
		return
	}

	// ------------- Required query parameter "end_period" -------------

	if paramValue := r.URL.Query().Get("end_period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end_period"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "end_period", r.URL.Query(), &params.EndPeriod, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_period", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "service_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "service_name", r.URL.Query(), &params.ServiceName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CalculateTotalCost(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubscriptions operation middleware
func (siw *ServerInterfaceWrapper) ListSubscriptions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSubscriptionsParams

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "service_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "service_name", r.URL.Query(), &params.ServiceName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service_name", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubscriptions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSubscription operation middleware
func (siw *ServerInterfaceWrapper) CreateSubscription(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSubscription operation middleware
func (siw *ServerInterfaceWrapper) DeleteSubscription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subscription_id" -------------
	var subscriptionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "subscription_id", chi.URLParam(r, "subscription_id"), &subscriptionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subscription_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSubscription(w, r, subscriptionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubscription operation middleware
func (siw *ServerInterfaceWrapper) GetSubscription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subscription_id" -------------
	var subscriptionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "subscription_id", chi.URLParam(r, "subscription_id"), &subscriptionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subscription_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscription(w, r, subscriptionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSubscription operation middleware
func (siw *ServerInterfaceWrapper) UpdateSubscription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subscription_id" -------------
	var subscriptionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "subscription_id", chi.URLParam(r, "subscription_id"), &subscriptionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subscription_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSubscription(w, r, subscriptionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/reports/total-cost", wrapper.CalculateTotalCost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/subscriptions", wrapper.ListSubscriptions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/subscriptions", wrapper.CreateSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/subscriptions/{subscription_id}", wrapper.DeleteSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/subscriptions/{subscription_id}", wrapper.GetSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/subscriptions/{subscription_id}", wrapper.UpdateSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W7byBV+FWK6Fy1ASZTiOIjummzbDZq0QTa5MAzVYKSRza1EMuQoiOsKkKXsegMb",
	"MZCbFm03i7QvQDtWrFiW8gpn3qg4M5TEn5FkObaTAHuzkDYm5zvnfOc7P6MtUnbqrmNTm/mkuEU86ruO",
	"7VPx5ZZZeUCfNKjP8FvZsRm1xUfTdWtW2WSWY+e+8x0b/59f3qB1Ez995dEqKZJf5Savzsl/9XO/8zzH",
	"exAeQprNpk4q1C97losvI0UCP0EXTmDIW7yFn3gbBnwXuhp8gIC3IIBT6PI2b/FdDY4hgA+8BUO+DUGW",
	"NHVy27GrNat8lYD/BUMY8OfQhx7C1eAIAhggav69wHTHZtSzzZp41RUCewUD3kFXQVfg2ef7Ggz5j9CD",
	"AziBQOPb0OUtOBT/lf77k8N+7zTsyhXC/AcGEXp8m+9pMMBIDyCA93AkYCOsph4eJlh526Mmo982Ho/f",
	"EiGp6zku9ZglCUztylrFZHQeyHuOzTZWqOmhC1zPKosnEjjf8DYMoQenSDfeRrRIxW2+z3dgAEN4jxwd",
	"wpG0Bk6gp8Ghxlu8AwfQ5/tIB53QZ2bdrVFSXDIMndQt26o36qSY1wnbdCkpEstmdJ0KKD71nlplumab",
	"dRWinyCAYzgUdOtBdxJPPD7QNZEbXTiSgCGAQwHjJX8BXXgLwwRe3onhIyumXaHPtPu1hk90Ujef3aX2",
	"OtsgxcL16wL56PsEu888y14X0JnpscWd3/Cpt2ZVFMb+UxKCt6HHn2OqQYAB4S1pRZ/vwTEM0Ru8DV00",
	"NG7NsrFs5KuUZgqPq/nM0o1CPmPS5WrmxvK1ZXrjpmmUH5tEJ1XHq5uMFEmjYVVIyrCmTjz6pGF5tEKK",
	"q/EAjagzsSLmhtL4Zc7j72iZobnx7Ejxt05931xXhf6/Qhu3UW4mGd3LzgU8eqMKzCQQ6fP+EzL9Bw1Z",
	"/RZpI8j9HCMAp9Lp2r17mZWVlZW4440bmYJRuI7uMRkqISmSv/zaWM1nbpb+nl81MoXSbzKrRuZmaWup",
	"+RVRcCma63ctn013mMVoPf5hFvPiGjKSqDEA0/PMTfxes+oWUzjl30INehiEQ76Lus93YkGIpLJTrfpU",
	"9ZI3QkVeCLHDJJ7/KuYws6Z402s4EO/palhAsR7xHRG2Nhxish+PhBa68F7XeAeVATUBCyr+CW+F6tDj",
	"32siyfp8TxSQAE6z0eSwbLa8pACXYJuMwgjxyJFjZ6hIqIzJxQj7orIy8VcvO18ZLr1wfB7l4XMV+sV0",
	"W2rzR4r3Q2T1bWeWHpUbnkft8qbCzFcQQJ+/RMdrmGF8W2RrGzueqHw+eHRL5XbMAJd6llNZyO3SpHM8",
	"KFJ4rez4Sg3jHTgVVaCFLRvf1wSjEqSPsmkIJyLBpNwdCIkRPbNMBuRpb1xkpnVQBdFCzdGgCHB9Eo+E",
	"J2L+VMX6kVv5kpvOz6/N/DLbyavsDvFtll110uB/e/8OTpl9zLOO8H4gyzgGCIc8tQV7kh/Ysmg4s0Jf",
	"zFmDTIJBgfyLXkKWNNkWbMdyHQmYzHV8WKR2JI9F6bCYUDR4M+GPBgG8FfR5CwH/AXozsQ3hhOjkKfV8",
	"6Yh81sgaortyqW26FimSa1kje032mhsiHXOma+We5nMedR2P+TmhB5mRkK0re7JXMETGC/tfQID2Jwzn",
	"Hf7y4kSObyfaLeGJbpjc0+L5UvTig2h2ClDR7ES/oziJ0f1OhRTJbbNWbtRMRsflS3jLM+uUUc8nxVWV",
	"APAdLFcSyxi3sGzGDGDh008a1EO9leKSlN1JujCvQfUzLhUiOd7Ut5QLGejirPKRYCNF4XKgLq5CCiMe",
	"Pbrz9TQLIlozhjtXxBasAKkKNDX2cT2cIFqoGDRLenxNWTCMC1tXpXs61crqY/qdmCg2dbIk0atAja3M",
	"RTaxTZ1cP8sj8a2j2KE16nXT20QDfhYod3B2RRLxvXPKG7LHXEfRIPCat2Wp4LukhOeNlNePdE3+oqIb",
	"9V/SoVg+DsVTpzCEd1iOJE4En9bT3iWo6V3LZ9/G7Jsnpr+k/DlSXlcspAI4wdEcfSK8hs3ImVYf6E8Y",
	"in/CxqY7DftoWzEBXaFVs1FjpFgwRAcb9tTzFrkK+KmtD+IR/BU52R1ZJBgZFt9gkg4nkosq1OFuRQk7",
	"ilM1OV2msk5d4ikFdkbaf1LVhD7vSN0UmjkDZlQaf44nCynhxDdllBZ6dhTqnyD1oVDjCYdRh5NDlbwg",
	"mzq3JFrA1A1K2N5Qn91yKpsXFvPpVzXN+KyEHVUzRb78pZBvJvHikQo03hFB7vIfRTaK0B6HN3zBeZm4",
	"ZNyc/8j4JvNCqDumVbqMn/DObK5OK+W5rejXNavSlHyuUaZaI/xPuK3P9yWzz0JnTW6ze9NKplwlxMn9",
	"tTg/Re4YsZYU8NKRl3jHt5DnDPXS/EfGl64XEurQz6FGLRZqfYHe7NIi+AfKZofP+PS6kLqj/lLYkaxh",
	"SX6EUZsRsLmF7bztb+S+RcWnccPjmmwj0mHGNWjmoD6vDS7pxG2wKeLQj80XMIQDWZ3HkoYjFLZ0su3E",
	"os1fnKl0p1MgvW6+pAo9fa99pgr9OWRiJBBXnI2foI6/HhvbO2cl36BmjW38bbE5vGAY2p//qGtIbiwt",
	"2jcPH97PRGfC0Y+xOnKoEcP0B7HoGIQz2qRmyF9s8V2l9H8T4pvLNUafsZxbM60EyyZXZ85fFTmuGjYi",
	"VoS3GLyDXR8Msin9RPDhT6bCEEQfGUtEYmCOxiVyHsYkvIAZ6WXDq5EiyREUo/ARxZDQ5x14B11kg/x1",
	"3DBcLI1WHanjQ7mMna4YTF8n3zP1giFxYRA5Ikm8MxyjuAZQXSukZ6zRmdHtU7PU/H8AAAD///8RNzLY",
	"KAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
